### ISSUE TITLE
Avatar size in Author_info not respecting configured size

### ISSUE THREAD

**Issue by Ruud68** [shondalai/cjblog#10]
Not all avatar providers have the functionality to create multiple thumbnailsizes like cjbog does.
Easy Profile has two avatars: the original (in my case configured to 200x200) and a thumbnail (50x50)

#### Issue
When displaying the avatar in the author_info (layout) the image is retreived via the cjlib api. The api function getUserAvatarImage returns the original Easy Profile avatar (size 200x200). the layout author_info will display the avatar with the 200x200 size NOT respecting configured size $params->get('article_avatar_size', 96);

#### Expected result
All avatars (from all avatar providers) should be able to display the avatar in the configured size

#### Proposed solution
Change
`....style="min-width: <?php echo $avatarSize;?>px;">`
to
`style="max-width: <?php echo $avatarSize;?>px;">`

in layout/author_info.php

#### Next step
If we can agree on this change I can create a PR for that.

**Comment by corejoomla** [comment]
I would suggest to have both min-width and max-width as some templates by default apply zero size to the images and make them show as a dot. We do not have control over the other templates so we should have some workaround at our side.

**Comment by Ruud68** [comment]
Okay, just added the max-width. Please note that in ./views/leaderboard/tmpl/default.php you use only the max-height and not the combination. So that might give issues as you described :)
