### ISSUE TITLE
Add Easy Profile as avatar and profile provider

### ISSUE THREAD

**Issue by Ruud68** [shondalai/cjblog#11]
In version 1.4.2 we worked on adding Easy Profile as avatar and profile (and profile text) provider.

#### Issue
Easy Profile is not is the dropdown list as provider for the avatar and for the profile page

#### Expected result
Easy Profile should be selectable as provider in both the Avatar and profile page

#### Proposed solution
Add Easy Profile as option in administrator/components/com_cjblog/config.xml
for fields:
profile_component and avatar_component

This will work as the actual logic for Easy Profile's avatar and profile page URL is still in cjlib/api

#### Next step
If we can agree on this change I can create a PR for that.

**Comment by corejoomla** [comment]
Agree. Required avatar logic is already available in CjLib component. So adding the option will suffice to show EasyProfile avatar.

**Comment by Ruud68** [comment]
Cool :)
