### ISSUE TITLE
Pro-capabities not working correct

### ISSUE THREAD

**Issue by Ruud68** [shondalai/cjblog#13]
In version 1.4.2 we added the pro-capabilities functionality. That functionality was to configure via ACL a Joomla group that would have additional functionalities:
1. About text would be displayed
2. Avatar would link to profile page
3. Name would link to profile page

When a user was NOT member of the configured Joomla Group the above three rules would not apply (no about text, no links to user profile)

#### Issue
Version 2.0 only handles the about text via the pro-capability and not the avatar and profile link.
When an author is NOT member of the pro-capability ACL his avatar and name will still link to his profile.

#### Expected result
When an author is NOT member of the pro-capability ACL his avatar and name should NOT link to his profile.

#### Proposed solution
There are two possible solutions for this:
1. add pro-capability check to api/getUserProfileUrl
2. add pro-capalitity to all cjlog views / layouts that call api/getUserProfileUrl (this is how it was handled in 1.4.2)

#### Next step
I think this change should be part of cjlib/api/getUserProfileUrl because then you do one change and change it for all current and future functionality.

**Comment by corejoomla** [comment]
The later option of checking necessary things at the layout is more desirable as it is CjBlog specific check. API applies to every other component.

**Comment by Ruud68** [comment]
Okay agree :), that would mean changes to all views / layouts on the cjblog side. I will first come up with a change in code that we can agree upon and then (if agreed) do a PR for all the changes.

**Comment by Ruud68** [comment]
Okay, just found out that core.pro ACL is not implemented at all, so my first observation that it was only working for the about text was NOT correct (it turned out that I tested with a user who didn't have about text :)

I propose to change it with the following logic (for the article view)
in ./plugins/content/cjblog/cjblog.php (where the about text is filled)
```
                        // Check if author has pro-capabilities
                        $proUser = JFactory::getUser($article->created_by)->authorise('core.pro', 'com_cjblog');

                        if (!$proUser)
                        {
                                $profile['about'] = '';
                        }
                        elseif($aboutTextApp == 'easyprofile')
                        {
                                $db = JFactory::getDbo();
                                $query = $db->getQuery(true)
                                        ->select($db->qn($db->escape($appParams->get('easyprofile_about_field', 'author_info'))).' AS about')
                                        ->from('#__jsn_users')
                                        ->where('id = '. $article->created_by);

                                $db->setQuery($query);
                                $profile['about'] = $db->loadResult();
                        }
```

and in ./components/com_cjblog/layouts/default/author_info.php where the link on the avatar is placed
```
$profileApp             = $params->get('profile_component', 'cjblog');
$avatarSize             = $params->get('article_avatar_size', 96);

// Check if author has pro-capabilities
$proUser                = JFactory::getUser($article->created_by)->authorise('core.pro', 'com_cjblog');
$userProfileUrl         = ($proUser ? $api->getUserProfileUrl($profileApp, $article->created_by) : '#');
```
and then for the actual generation of the avatar:
```
<a href="<?php echo $userProfileUrl;?>" class="thumbnail">
```

**Comment by corejoomla** [comment]
Looks good. Please send me the PR.
