### ISSUE TITLE
Missing Article / author info on top of article

### ISSUE THREAD

**Issue by Ruud68** [shondalai/cjblog#14]
Not sure if this is intended or not :)

#### Issue
the Article view is 'missing' the article / author / social Media sharing info on the top of the article

#### Expected result
There should be a info box (configurable to show / hide) on top of the article showing:
author avatar, author name (both linked to profile if pro-capabilities)
hits, hot or not, category, etc.
Social Media sharing buttons.

#### Proposed solution
add a additional layout that will be added via the cjblog content plugin to the article text vai this line of code:
`$article->text 		= '<div id="cj-wrapper">' . $toolbarHtml . $titleHtml . $tagsHtml . $imagesHtml . $article->text . $socialSharingHtml . $authorInfoHtml . '</div>';`

#### Next step
Discuss if this is left out intentionally, if not and it needs to be readded a layout (design / functionality) should be discussed.

**Comment by corejoomla** [comment]
It's in the new layout file components/com_cjblog/layouts/default(or bootstrap3)/author_info.php

**Comment by Ruud68** [comment]
I understand, but that is the author info box below the article (which looks great by the way :)).
What I am referring to is the info above the article
![image](https://cloud.githubusercontent.com/assets/2733197/24836160/9e9ca26c-1d14-11e7-949b-2d3b3b042c7d.png)

**Comment by corejoomla** [comment]
Got it. Somehow this block is missing. I propose a new layout file (author_info_top.php) which includes the author info top block and tags (if present).

**Comment by corejoomla** [comment]
Added following missing options in the new commit

- Show Article Info
- Show Avatar
- Show Author Name
- Show Category
- Show Date
- Show Hits
- Hot Article Hits

**Comment by corejoomla** [comment]
A sample screenshot of how the info looks at bottom (same can be displayed on top). Author about text will be displayed only at the bottom.

![image](https://user-images.githubusercontent.com/4133237/27661848-29de8a3a-5c5c-11e7-8ef5-96cfac9e7376.png)

**Comment by corejoomla** [comment]
Added following missing options in the new commit

Show Article Info
Show Avatar
Show Author Name
Show Category
Show Date
Show Hits
Hot Article Hits

A sample screenshot of how the info looks at bottom (same can be displayed on top). Author about text will be displayed only at the bottom.

![image](https://user-images.githubusercontent.com/4133237/27661848-29de8a3a-5c5c-11e7-8ef5-96cfac9e7376.png)
