### ISSUE TITLE
Article images handled by cblog content plugin corrupting template

### ISSUE THREAD

**Issue by Ruud68** [shondalai/cjblog#17]
Hi,
one of the features of template (eg Gavick) is the special position etc. they have in the template for fulltext images

### Issue
when enabling cjblog the displayed article is 'corrupted' when it comes to the placement of the fulltext image

### Expected result
Fulltext image should be handled by the template OR by cjblog

### Proposed solution
Create a configuration option with which you can disable handling the full text image by cjblog in the plg_content_cjblog

### Next step
Discuss if this is an option, if so I can do a PR for that.

Screenshot with cjblog (fulltext image handled by plg_content_cjblog)
![selection_143](https://cloud.githubusercontent.com/assets/2733197/24861532/5bac1e8e-1df9-11e7-97b6-3d4464899590.jpg)

Screenshot without cjblog (fulltext image handled by template)
![selection_144](https://cloud.githubusercontent.com/assets/2733197/24861562/776fa820-1df9-11e7-8215-826f6c06d09a.jpg)

**Comment by corejoomla** [comment]
Ideally it should be handled by the plugin itself. However if the template has hardcoded code, it is difficult for us to handle situation. In such cases the only option for us is to disable within plugin. So I accept your solution.

**Comment by corejoomla** [comment]
New configuration option is added to control the image display handling.
