### ISSUE TITLE
An error has occurred. 0 Call to undefined method Joomla\CMS\Form\Field\EditorField::save() - CjBlog Component on Joomla 4

### ISSUE THREAD

**Issue by lmadonna** [shondalai/cjblog#20]
When clicking on a user in  the "User Manager" page of the CJBlog component , the error (An error has occurred. 0 Call to undefined method Joomla\CMS\Form\Field\EditorField::save()) appears.
My Joomla version is  4.2.8. and I have installed cjlib_v3.3.2.zip and cjblog_v3.0.3.zip.

**Comment by boddunan** [comment]
PR #21 will fix this bug.

**Comment by lmadonna** [comment]
I've verified the #20 error  fix,  replacing new delivered files : 

                              1) /administrator/components/com_cjblog/views/profile/tmpl/edit.php
                              2) /media/com_cjblog/css/cj.blog.min.css
                              3) /media/com_cjblog/js/cj.blog.js
                              4) /media/com_cjblog/css/cj.blog.min.css
on my Joomla (vers. 4.2.8) site on Altervista hosting.
Already after replacing the file in point 1) the reported problem is solved.
Thanks and bye.
